# Generated by Django 2.2.7 on 2019-12-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_recipe_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mod_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
