# Generated by Django 2.2.7 on 2019-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20191204_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('TSP', 'tsp'), ('TBSP', 'tbsp'), ('C', 'c'), ('FL_OZ', 'fl oz'), ('QT', 'qt'), ('PT', 'pt'), ('GAL', 'gal'), ('ML', 'ml'), ('L', 'l'), ('DL', 'dl'), ('OZ', 'oz'), ('LB', 'lb'), ('MG', 'mg'), ('G', 'g'), ('PINCH', 'pinch')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_units',
            field=models.CharField(choices=[('MINS', 'minutes'), ('HRS', 'hours')], default='MINS', max_length=50),
        ),
    ]
