# Generated by Django 2.2.7 on 2019-12-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20191204_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
