# Generated by Django 2.2.7 on 2020-02-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20191204_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement',
            new_name='quantity',
        ),
    ]
